var express = require('express');
var controllers = require('./controllers');
var router = express.Router();

router.post('/menu',controllers.menu);
router.post("/menui",controllers.completeMenu);
router.post("/getMenu",controllers.getMenu);
router.post("/deleteMenu" , controllers.deleteMenu);
router.post("/menuCategory",controllers.menuCategory);
router.post("/updateMenuCategory",controllers.menuCategoryUpdate);
router.post("/deleteMenuCategory",controllers.menuCategoryDelete);
router.post("/findMenuCategory",controllers.getMenuCategory);
router.post("/menuCustomisation",controllers.menuCustomisation);
router.post("/findMenuCustomisation",controllers.getMenuCustomisation);
router.post("/updateMenuCustomisation",controllers.menuCustomisationUpdate);
router.post("/deleteMenuCustomisation",controllers.menuCustomisationDelete);
router.post("/menuCategoryItems",controllers.categoryItems);
router.post("/findMenuCategoryItem",controllers.findMenuCategoryItem);
router.post("/updateMenuCategoryItem",controllers.updateMenuCategoryItem);
router.post("/deleteMenuCategoryItem",controllers.deleteMenuCategoryItem);
router.post("/menuCustomisationOptions",controllers.customisationOptions);
router.post("/findMenuCustomisationOptions",controllers.findMenuCustomisationOptions);
router.post("/updateMenuCustomisationOption",controllers.updateMenuCustomisationOption);
router.post("/deleteMenuCustomisationOption",controllers.deleteMenuCustomisationOption);
router.post("/itemCustomisation",controllers.itemCustomisation);
router.post("/categoryCustomisation",controllers.categoryCustomisation);
router.post("/getCategoryCustomisation",controllers.getCategoryCustomisation);
module.exports = router;